"""add shared columb

Revision ID: 4d92085bf163
Revises: ae81f67d348f
Create Date: 2016-09-02 10:24:06.728000

"""

# revision identifiers, used by Alembic.
revision = '4d92085bf163'
down_revision = 'ae81f67d348f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zhulong_docker', sa.Column('shared', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zhulong_docker', 'shared')
    ### end Alembic commands ###
