"""empty message

Revision ID: 6d017f7e0c5d
Revises: 8e77c8327a29
Create Date: 2016-09-24 19:47:11.602000

"""

# revision identifiers, used by Alembic.
revision = '6d017f7e0c5d'
down_revision = '8e77c8327a29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zhulong_op_system', sa.Column('image_id', sa.String(length=12), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zhulong_op_system', 'image_id')
    ### end Alembic commands ###
