"""add base component and type models

Revision ID: 8e77c8327a29
Revises: c09ff6b5b948
Create Date: 2016-09-06 22:27:54.556000

"""

# revision identifiers, used by Alembic.
revision = '8e77c8327a29'
down_revision = 'c09ff6b5b948'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhulong_base_component_type',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('type_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zhulong_base_components',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('components_type', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('components_name', sa.String(length=64), nullable=True),
    sa.Column('components_version', sa.String(length=32), nullable=True),
    sa.Column('components_url', sa.String(length=256), nullable=True),
    sa.Column('components_image', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zhulong_base_components')
    op.drop_table('zhulong_base_component_type')
    ### end Alembic commands ###
