"""empty message

Revision ID: ae81f67d348f
Revises: 39b61b9700c2
Create Date: 2016-08-31 22:12:10.422000

"""

# revision identifiers, used by Alembic.
revision = 'ae81f67d348f'
down_revision = '39b61b9700c2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhulong_docker',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=True),
    sa.Column('docker_name', sa.String(length=32), nullable=True),
    sa.Column('docker_description', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zhulong_docker_docker_name'), 'zhulong_docker', ['docker_name'], unique=False)
    op.create_table('zhulong_docker_info',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('docker_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=True),
    sa.Column('docker_tag', sa.String(length=64), nullable=True),
    sa.Column('docker_image_id', sa.String(length=12), nullable=True),
    sa.Column('op_system', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('ssh_port', mysql.INTEGER(display_width=5, unsigned=True), nullable=True),
    sa.Column('ssh_password', sa.String(length=16), nullable=True),
    sa.Column('ssh_user', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('last_start_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zhulong_op_system',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('op_name', sa.String(length=32), nullable=False),
    sa.Column('image_name', sa.String(length=32), nullable=False),
    sa.Column('image_url', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zhulong_op_system')
    op.drop_table('zhulong_docker_info')
    op.drop_index(op.f('ix_zhulong_docker_docker_name'), table_name='zhulong_docker')
    op.drop_table('zhulong_docker')
    ### end Alembic commands ###
