"""fix opsystem table, add version column

Revision ID: c09ff6b5b948
Revises: 4d92085bf163
Create Date: 2016-09-06 21:23:40.247000

"""

# revision identifiers, used by Alembic.
revision = 'c09ff6b5b948'
down_revision = '4d92085bf163'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zhulong_op_system', sa.Column('version', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zhulong_op_system', 'version')
    ### end Alembic commands ###
