"""empty message

Revision ID: dae9306dc06c
Revises: 83565fa196e6
Create Date: 2016-10-17 22:58:44.203000

"""

# revision identifiers, used by Alembic.
revision = 'dae9306dc06c'
down_revision = '83565fa196e6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zhulong_shared_images', 'image_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_shared',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_system_images', 'image_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('zhulong_system_images', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_user', 'blocked',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('zhulong_user_containers', 'container_id',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('zhulong_user_containers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('zhulong_user_containers', 'is_running',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zhulong_user_containers', 'is_running',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_user_containers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_user_containers', 'container_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('zhulong_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('zhulong_user', 'blocked',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_system_images', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_system_images', 'image_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_shared',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_locked',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('zhulong_shared_images', 'image_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    ### end Alembic commands ###
