"""empty message

Revision ID: ddf1e4277864
Revises: 6d017f7e0c5d
Create Date: 2016-09-27 22:39:04.719000

"""

# revision identifiers, used by Alembic.
revision = 'ddf1e4277864'
down_revision = '6d017f7e0c5d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhulong_shared_images',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('owner_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('image_id', sa.String(length=12), nullable=True),
    sa.Column('image_name', sa.String(length=32), nullable=True),
    sa.Column('image_description', sa.String(length=255), nullable=True),
    sa.Column('exposed_port', sa.String(length=512), nullable=True),
    sa.Column('parent_image', sa.String(length=512), nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zhulong_system_images',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('op_name', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('image_name', sa.String(length=32), nullable=True),
    sa.Column('image_id', sa.String(length=12), nullable=True),
    sa.Column('expose_port', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zhulong_user_containers',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('owner_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('image_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('image_type', mysql.TINYINT(display_width=2, unsigned=True), nullable=True),
    sa.Column('container_name', sa.String(length=64), nullable=True),
    sa.Column('container_id', sa.String(length=12), nullable=True),
    sa.Column('ssh_user', sa.String(length=32), nullable=True),
    sa.Column('ssh_port', mysql.INTEGER(display_width=5, unsigned=True), nullable=True),
    sa.Column('ssh_password', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_running', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('last_run_time', sa.DATETIME(), nullable=True),
    sa.Column('last_stop_time', sa.DATETIME(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('zhulong_base_components')
    op.drop_table('zhulong_docker')
    op.drop_table('zhulong_base_component_type')
    op.drop_table('zhulong_docker_info')
    op.drop_table('zhulong_op_system')
    op.add_column('zhulong_user', sa.Column('blocked', sa.BOOLEAN(), nullable=True))
    op.add_column('zhulong_user', sa.Column('updated_time', sa.DATETIME(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zhulong_user', 'updated_time')
    op.drop_column('zhulong_user', 'blocked')
    op.create_table('zhulong_op_system',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('op_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('image_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('image_id', mysql.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('zhulong_docker_info',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('docker_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('docker_tag', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('docker_image_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('op_system', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ssh_port', mysql.INTEGER(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ssh_password', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('ssh_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('last_start_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('zhulong_base_component_type',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('type_name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('zhulong_docker',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('docker_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('docker_description', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('created_time', mysql.DATETIME(), nullable=True),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.Column('shared', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('zhulong_base_components',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('components_type', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('components_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('components_version', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('components_url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('components_image', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('zhulong_user_containers')
    op.drop_table('zhulong_system_images')
    op.drop_table('zhulong_shared_images')
    ### end Alembic commands ###
